### ISSUE TITLE
Which type of controller is best for his Add-on?

### ISSUE THREAD

**Issue by anthonyalvarez** [roxgib/anki-contanki#12]
Hello from New York City!

Which game pad works best with Anki-contanki: Xbox, PlayStation or another compatible brand?
Which type of game pad offers the best performance with Anki-contanki?

Also does Anki-contanki also work with Anki installed on an Android phone? 
Looking forward to trying this Anki-contanki. Thank you.

**Comment by roxgib** [comment]
AnkiDroid doesn't support add-ons, which are only for the desktop editions. I know the iOS version of Anki has builtin support for controllers, but I don't use AnkiDroid so I can't really help you there.

As a first step you can use [this website](https://gamepad-tester.com) to confirm that your gamepad is compatible with the HTML5 gamepad library. If it isn't detected by that site it won't work with Contanki, but still feel free to post here if that happens because it probably just means your controller isn't connected properly.

I've done most of my own testing with a DualShock 4, but any non-third party Xbox or Playstation controller from the last two or three generations should work out of the box. Support for Nintendo gamepads such as Joy Cons is currently a bit limited as they tend to use unusual layouts. Third-party controllers are a bit more of a mixed bag, but most should work out of the box. Some may have incorrect layouts or not be recognised properly, particularly if they have non-standard controls. Either way, post here and it's usually pretty easy to add support for them. 

Additionally, look in the usage notes in the main readme or on the add-ons page on AnkiWeb for some on known issues with certain controllers or platforms

I'm going to close this as it's not an outstanding issue but you can still reply if you have more questions.
