### ISSUE TITLE
New Update (10/24/22) did not fix Add-On for me

### ISSUE THREAD

**Issue by Lou-Rye** [roxgib/anki-contanki#30]
I just updated the contanki add-on, and I am still getting the same message as before (I made sure to close and reopen Anki for the changes to take effect). It still can't recognize my 8bitdo controller.

This is the error message I am getting:
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-24 08:25:58

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 123, in on_receive_message
    funcs[func](*args)
  File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 329, in on_connect
    _controller = identify_controller(
  File "C:\Users\Owner\AppData\Roaming\Anki2\addons21\1898790263\controller.py", line 134, in identify_controller
    device_name = controller_ids["devices"][vendor_id][device_id]
KeyError: None

Can this be fixed? I'd appreciate if it could! Thanks again

**Comment by RyanShahidi** [comment]
I recieve the same error and have since the first update a couple of days ago. Additionally, I am unable to even get into the config menu (By clicking tools->Add-ons->Config) and I get this error. I have tried uninstalling, reinstalling, and restarting my computer with no change

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-24 08:40:39

Caught exception:
Traceback (most recent call last):
  File "aqt.addons", line 962, in onConfig
  File "C:\Users\ryans\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 104, in on_config
    ContankiConfig(focus, self.profile)
AttributeError: 'Contanki' object has no attribute 'profile'

**Comment by slobbytoppy** [comment]
Similar issue, Anki was able to recognize 8BitDo controller this AM, but now getting error.


Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-24 14:53:24
Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "/Users/brandon/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 123, in on_receive_message
    funcs[func](*args)
  File "/Users/brandon/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 384, in register_controllers
    con = identify_controller(*(controller.split("%%%")))
  File "/Users/brandon/Library/Application Support/Anki2/addons21/1898790263/controller.py", line 134, in identify_controller
    device_name = controller_ids["devices"][vendor_id][device_id]
KeyError: None

**Comment by roxgib** [comment]
Apologies everyone, a few bugs creeped in due to the size of the update, and I'm squashing them now. This should be fixed with [6c6bec3](https://github.com/roxgib/anki-contanki/commit/6c6bec31b5db361e1a955a97415999765c033f82) which is in the latest beta. Would you be able to confirm that it's fixed?

Also, assuming it's indeed fixed, it would be helpful if everyone experiencing this could open up the controller options, click help, and paste the text that's there. This problem affects controllers that aren't identifiable by their ids, and it would be helpful going forward to identify those controllers.

**Comment by Lou-Rye** [comment]
> Apologies everyone, a few bugs creeped in due to the size of the update, and I'm squashing them now. This should be fixed with [6c6bec3](https://github.com/roxgib/anki-contanki/commit/6c6bec31b5db361e1a955a97415999765c033f82) which is in the latest beta. Would you be able to confirm that it's fixed?
> 
> Also, assuming it's indeed fixed, it would be helpful if everyone experiencing this could open up the controller options, click help, and paste the text that's there. This problem affects controllers that aren't identifiable by their ids, and it would be helpful going forward to identify those controllers.

I am very happy to say that it works again, just like it used to! I had to reconfigure the buttons on my 8bitdo controller, but I don't mind at all. 

Thank you so much for creating/maintaining this add-on! You are saving my back/neck from a lot of pain :)

**Comment by slobbytoppy** [comment]
fixed, info you asked for:

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-25 06:08:58

2 controllers detected:
DUALSHOCK 4 Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 05c4)
Buttons: 18
Axes: 4

DUALSHOCK 4 Wireless Controller (STANDARD GAMEPAD)
Buttons: 16
Axes: 4

**Comment by RyanShahidi** [comment]
I use an 8BitDo zero 2. Would this be a similar issue to why the app crashes when the controller turns off?


Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-25 07:57:33

2 controllers detected:
Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 05c4)
Buttons: 18
Axes: 4

̢Surface Touchpad (Vendor: 045e Product: 09af)
Buttons: 0
Axes: 3

**Comment by roxgib** [comment]
Thanks everyone.

@RyanShahidi Nope, unrelated, just a new bug that crept in
