### ISSUE TITLE
Custom settings gone after closing anki

### ISSUE THREAD

**Issue by brushplain** [roxgib/anki-contanki#47]
Tittle says it all. This is even after pressing save. I'm using an Joy-Con controller. Anki version 2.1.54

**Comment by brushplain** [comment]
This has also come up in the reviews on the add on page

**Comment by brushplain** [comment]
This add on is has made life so much easier by allowing me to do review with my Joy-Con controller. Even without it saving custom settings, its still worth it to have this add-on. I simply re-enter my settings each day. With this being said, I would really appreciate if the author could fix this add-on soon. Especially for those who are in medical school, I'm sure they would be extremely gratefull. You could add a link for people of give donations in the config dialog. You could mention how much time it goes into developing and maintaining something like this. Medical students like myself pretty much use your add-on all day, doing hundreds to more than a thousand cards per day. I'm sure some people would donate!

**Comment by Biozac** [comment]
I am also experiencing this issue, using an 8BitDo Zero controller.
Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 6.3.1 PyQt 6.3.1

I also want to second brushplain in thanking you for this addon, it is incredibly helpful.

**Comment by ss3vy** [comment]
I had the same issue with the 8BitDo Zero (Anki Version ⁨2.1.56).

The temporary solution I came up with is to edit the specific profile file manually. It can be found in the following directory (macOS):

~/Library/Application Support/Anki2/addons21/1898790263/profiles/

Another way to access it is through Anki (Tools -> Add-ons -> Select Contanki -> Click "View Files" -> then go into the profiles folder). This method should work on Windows as well. 

Just open the relevant controller file in your favorite text editor (e.g. Sublime Text) and assign actions or move them around. It takes a little bit of reading since the buttons are defined as numbers, but the file is really well formatted and you can figure out which button is which by looking at the default assignments. 

A big THANK YOU to Sam and everyone else for writing this add-on! Med students everywhere are grateful for your work ♥️.

**Comment by roxgib** [comment]
Apologies for the delay in fixing this issue, and thank you to everyone who helped by reporting it. It should be resolved in the latest version of the add-on.
