### ISSUE TITLE
Xbox controller not working with new update on Mac

### ISSUE THREAD

**Issue by kmd1114** [roxgib/anki-contanki#50]
I installed the new update and now my xbox controller has no functionality on Anki. None of my mapped keys work, the only thing working is scrolling up and down.

**Comment by roxgib** [comment]
Sorry to hear about this. Can you tell me what time of Xbox controller it is?

**Comment by rsorto421** [comment]
I am having a similar issue at first I thought it was associated with my M1 MacBook Pro. But I discovered that I had no issues and everything worked as it should on my desktop which is a 2013 Mac Pro. My desktop runs the Q5 version of Anki while I have the Apple silicon Q6 version on my laptop. I had a similar issue when I installed the updated Q6 version on my desktop. Whenever I connect my Xbox One controller (1708) to a machine running the Q6 version of Anki It will not correctly map all the buttons and it will go haywire, causing me to force quit the app since I lose control of the mouse.
