### ISSUE TITLE
Overlay on top of another plugin

### ISSUE THREAD

**Issue by markhavemann** [roxgib/anki-contanki#52]
I've got another plugin that shows information on the top of the review screen and the overlay overlaps this a bit. Is there a setting to move the overlay down? I can't seem to find one. 

I think it might be useful to be able to tweak the location (and potentially the size) of the overlay, to be more flexible with different card layouts, plugins etc.

![clipImage_02022023104228](https://user-images.githubusercontent.com/2283022/216218145-cdc775ce-c276-442d-8b52-e98b10a56c34.png)

**Comment by roxgib** [comment]
The overlay is mainly intended for you to pull up if you forget a button binding or to access the quick select menu rather than left up permanently. I think you'll find once you've been using it for a little while you won't need it any more except occasionally. 

If you want to make sure you hit the right button when reviewing there are add-ons which display which answer you chose.

**Comment by markhavemann** [comment]
Thanks for the reply! I am already starting to not really need the overlay, so I guess I posted too soon on this!
