### ISSUE TITLE
8bitdo zero no up and down D-pad options?

### ISSUE THREAD

**Issue by AnKingMed** [roxgib/anki-contanki#63]
Is there a reason the up and down D-pad settings are not options? I only see left and right.

What I found worked well was to start the 8bitdo zero in Switch mode (dualshock 4 essentially) - I held Y+Start to do this.

I then changed the D pad to a joystick hat (digital input like the xbox dpad, not analog stick) and this worked.

For now I can just use the Dualshock 4 and have access to everything, but I have to push the buttons to see which button I need to adjust which is less convenient.

D pad setting options:
`Select + DPad Left - Set DPad to act as left analog stick. Select + DPad Right - Set Dad to act as right analog stick. Select + DPad Up - Set DPad to work as joystick hat (digital input like Xbox dpad, not an analog stick). Select + DPad Down - Swap buttons X/Y and A/B pairs`

![image](https://github.com/roxgib/anki-contanki/assets/57678116/6a9ae678-db8d-449e-9146-c1dc6cdd606b)

Absolutely love this add-on. If there's any way I can help or donate, let me know

**Comment by roxgib** [comment]
The 8BitDo Zero reports the D-pad like an analog stick, probably for compatibility with games that require a stick. In the add-on each axis can be set to different modes in the Options tab, and you have to set them to 'buttons' mode to be able to assign actions in the Controls tab. By default the horizontal axis is set to buttons, but the vertical axis is set to scrolling. A little counter intuitive when it's a D-Pad instead of an analog stick unfortunately. 

![Anki (Contanki Options) 2023 July 07 at 22 10PM](https://github.com/roxgib/anki-contanki/assets/33942237/570585ea-f824-4e29-8105-b8411398aada)

Let me know if you require any further clarification, and thanks for the support! I actually have next week off as I'm between contracts and I'm hoping to catch up on some of the pending issues with this add-on, so do let me know if there are any issues or suggestions!

**Comment by AnKingMed** [comment]
Thank you!

**Comment by AnKingMed** [comment]
Is there a way to invert the axis when scrolling?  If I set to buttons and scroll up/down, it scrolls too much and misses things in the middle. If I set the D pad to scroll vertically on the left/right axis, it is opposite of what I'd like

**Comment by roxgib** [comment]
Currently no, but this should probably be an option so I'll see about adding it.

**Comment by yash-fn** [comment]
Actually I thought I encountered somewhere in the documentation from 8bitdo a way to invert the axis. I don't remember how I did it, but the axis on mine is inverted. Look it up on their website and download their full length manual.

**Comment by roxgib** [comment]
The option to invert axes has now been added, so I'll close this
