### ISSUE TITLE
How do I connect contanki with another default controller (not xbox 360)

### ISSUE THREAD

**Issue by gearbike** [roxgib/anki-contanki#66]
It keeps conencting to default xbox 360 profile and makes my use of the software not seamless as I have to go into contanki settings everytime and switch it to the profile that I want to use.

**Comment by roxgib** [comment]
What controller are you using? Certain third party controllers identify themselves as first-party controllers. There is a setting to fix this for 8BitDo controllers.

That said, once you select a profile Contanki should remember that profile when you next connect the same controller. Are you saying that when you connect a controller it selects the default profile for that controller rather than the one you've configured yourself?
