### ISSUE TITLE
Doesn't work with Enhance main window

### ISSUE THREAD

**Issue by grossherr** [roxgib/anki-contanki#7]
Enhance main window
https://ankiweb.net/shared/info/877182321

No navigation in the main window, when I have it enabled. 

I mean, I just disabled above add-on for now, but maybe it's something to consider.

Thanks for your work!

**Comment by roxgib** [comment]
This is caused by that add-on dropping the `href="#"` from the deck names, making them non-selectable. You'll notice you also can't select the decks using Tab, unlike vanilla Anki. Unfortunately there's no workaround on my end, but I've submitted a fix so hopefully that will resolve it: 
https://github.com/Arthur-Milchior/anki-enhance-main-window/compare/master...roxgib:patch-1

**Comment by roxgib** [comment]
Should be good to go with the new version of enhance main window released today
